enum FinancialIntelligenceModelType {
  ordinarySpendingTotal,
  mandatorySpendingTotal,
  flexibleSpendingTotal,
  discretionarySpendingTotal,
  assetBuildingTotal,
  debtReductionTotal,
  cashMovementTotal,
  dataAdjustmentTotal,
  contextRequiredTotal,
  behavioralSavingsTotal,
  ordinarySpendingRatio,
  mandatoryRatio,
  flexibleRatio,
  discretionaryRatio,
}
