import 'package:flutter/material.dart';

abstract final class AppCategoryIcons {
  AppCategoryIcons._();

  static const String housing = 'housing';
  static const String groceries = 'groceries';
  static const String transport = 'transport';
  static const String restaurant = 'restaurant';
  static const String health = 'health';
  static const String shopping = 'shopping';
  static const String entertainment = 'entertainment';
  static const String education = 'education';
  static const String utilities = 'utilities';
  static const String insurance = 'insurance';
  static const String car = 'car';
  static const String savings = 'savings';
  static const String investment = 'investment';
  static const String salary = 'salary';
  static const String business = 'business';
  static const String freelance = 'freelance';
  static const String transfer = 'transfer';
  static const String other = 'other';
  static const String rent = 'rent';
  static const String mortgage = 'mortgage';
  static const String propertyTax = 'propertyTax';
  static const String condoFees = 'condoFees';
  static const String electricity = 'electricity';
  static const String naturalGas = 'naturalGas';
  static const String water = 'water';
  static const String sewer = 'sewer';
  static const String garbageCollection = 'garbageCollection';
  static const String internet = 'internet';
  static const String mobilePhone = 'mobilePhone';
  static const String homePhone = 'homePhone';
  static const String homeInsurance = 'homeInsurance';
  static const String homeMaintenance = 'homeMaintenance';
  static const String furniture = 'furniture';
  static const String appliances = 'appliances';
  static const String homeSupplies = 'homeSupplies';
  static const String homeSecurity = 'homeSecurity';
  static const String farmersMarket = 'farmersMarket';
  static const String cafe = 'cafe';
  static const String fastFood = 'fastFood';
  static const String foodDelivery = 'foodDelivery';
  static const String snacks = 'snacks';
  static const String alcohol = 'alcohol';
  static const String fuel = 'fuel';
  static const String evCharging = 'evCharging';
  static const String publicTransit = 'publicTransit';
  static const String taxi = 'taxi';
  static const String parking = 'parking';
  static const String tollRoads = 'tollRoads';
  static const String autoInsurance = 'autoInsurance';
  static const String autoLoan = 'autoLoan';
  static const String vehicleMaintenance = 'vehicleMaintenance';
  static const String tireService = 'tireService';
  static const String vehicleRegistration = 'vehicleRegistration';
  static const String carWash = 'carWash';
  static const String pharmacy = 'pharmacy';
  static const String medicine = 'medicine';
  static const String doctor = 'doctor';
  static const String dentist = 'dentist';
  static const String visionCare = 'visionCare';
  static const String medicalTests = 'medicalTests';
  static const String medicalProcedures = 'medicalProcedures';
  static const String healthInsurance = 'healthInsurance';
  static const String mentalHealth = 'mentalHealth';
  static const String physiotherapy = 'physiotherapy';
  static const String gymFitness = 'gymFitness';
  static const String vitamins = 'vitamins';
  static const String childcare = 'childcare';
  static const String daycare = 'daycare';
  static const String university = 'university';
  static const String tutoring = 'tutoring';
  static const String babySupplies = 'babySupplies';
  static const String toys = 'toys';
  static const String childSupport = 'childSupport';
  static const String clothing = 'clothing';
  static const String shoes = 'shoes';
  static const String cosmetics = 'cosmetics';
  static const String jewelry = 'jewelry';
  static const String haircare = 'haircare';
  static const String nailCare = 'nailCare';
  static const String personalHygiene = 'personalHygiene';
  static const String contactLenses = 'contactLenses';
  static const String movies = 'movies';
  static const String theatre = 'theatre';
  static const String concerts = 'concerts';
  static const String gaming = 'gaming';
  static const String streaming = 'streaming';
  static const String music = 'music';
  static const String books = 'books';
  static const String hobbies = 'hobbies';
  static const String travel = 'travel';
  static const String hotels = 'hotels';
  static const String courses = 'courses';
  static const String onlineLearning = 'onlineLearning';
  static const String universityTuition = 'universityTuition';
  static const String certifications = 'certifications';
  static const String conferences = 'conferences';
  static const String languageCourses = 'languageCourses';
  static const String educationalMaterials = 'educationalMaterials';
  static const String bankFees = 'bankFees';
  static const String atmFees = 'atmFees';
  static const String creditCardPayment = 'creditCardPayment';
  static const String loanPayment = 'loanPayment';
  static const String debtRepayment = 'debtRepayment';
  static const String emergencyFund = 'emergencyFund';
  static const String investments = 'investments';
  static const String currencyExchange = 'currencyExchange';
  static const String incomeTax = 'incomeTax';
  static const String driverLicence = 'driverLicence';
  static const String passport = 'passport';
  static const String immigrationFees = 'immigrationFees';
  static const String permits = 'permits';
  static const String governmentServices = 'governmentServices';
  static const String petFood = 'petFood';
  static const String veterinary = 'veterinary';
  static const String petMedicine = 'petMedicine';
  static const String petInsurance = 'petInsurance';
  static const String petGrooming = 'petGrooming';
  static const String petSupplies = 'petSupplies';
  static const String gifts = 'gifts';
  static const String charity = 'charity';
  static const String donations = 'donations';
  static const String holidayExpenses = 'holidayExpenses';
  static const String officeSupplies = 'officeSupplies';
  static const String software = 'software';
  static const String equipment = 'equipment';
  static const String businessTravel = 'businessTravel';
  static const String professionalMemberships = 'professionalMemberships';
  static const String licences = 'licences';
  static const String cashWithdrawal = 'cashWithdrawal';
  static const String adjustment = 'adjustment';
  static const String bonus = 'bonus';
  static const String overtime = 'overtime';
  static const String commission = 'commission';
  static const String tips = 'tips';
  static const String businessIncome = 'businessIncome';
  static const String consulting = 'consulting';
  static const String rentalIncome = 'rentalIncome';
  static const String interestIncome = 'interestIncome';
  static const String dividendIncome = 'dividendIncome';
  static const String capitalGains = 'capitalGains';
  static const String investmentDistribution = 'investmentDistribution';
  static const String taxRefund = 'taxRefund';
  static const String governmentBenefits = 'governmentBenefits';
  static const String pension = 'pension';
  static const String childBenefit = 'childBenefit';
  static const String employmentInsurance = 'employmentInsurance';
  static const String giftReceived = 'giftReceived';
  static const String familySupport = 'familySupport';
  static const String cashback = 'cashback';
  static const String rewards = 'rewards';
  static const String refund = 'refund';
  static const String reimbursement = 'reimbursement';
  static const String saleOfItem = 'saleOfItem';
  static const String otherIncome = 'otherIncome';

  static IconData fromKey(String key) {
    return switch (key) {
      housing => Icons.home_work_outlined,
      groceries => Icons.shopping_basket_outlined,
      transport => Icons.directions_bus_outlined,
      restaurant => Icons.restaurant_outlined,
      health => Icons.favorite_border_rounded,
      shopping => Icons.shopping_bag_outlined,
      entertainment => Icons.movie_outlined,
      education => Icons.school_outlined,
      utilities => Icons.electrical_services_outlined,
      insurance => Icons.policy_outlined,
      car => Icons.directions_car_outlined,
      savings => Icons.savings_outlined,
      investment => Icons.trending_up_rounded,
      salary => Icons.payments_outlined,
      business => Icons.business_center_outlined,
      freelance => Icons.work_outline_rounded,
      transfer => Icons.sync_alt_rounded,
      other => Icons.category_outlined,
      rent => Icons.home_outlined,
      mortgage => Icons.home_work_outlined,
      propertyTax => Icons.request_quote_outlined,
      condoFees => Icons.apartment_outlined,
      electricity => Icons.electrical_services_outlined,
      naturalGas => Icons.local_fire_department_outlined,
      water => Icons.water_drop_outlined,
      sewer => Icons.plumbing_outlined,
      garbageCollection => Icons.delete_outline_rounded,
      internet => Icons.wifi_outlined,
      mobilePhone => Icons.phone_android_outlined,
      homePhone => Icons.phone_outlined,
      homeInsurance => Icons.security_outlined,
      homeMaintenance => Icons.build_outlined,
      furniture => Icons.chair_outlined,
      appliances => Icons.kitchen_outlined,
      homeSupplies => Icons.inventory_2_outlined,
      homeSecurity => Icons.shield_outlined,
      farmersMarket => Icons.storefront_outlined,
      cafe => Icons.local_cafe_outlined,
      fastFood => Icons.fastfood_outlined,
      foodDelivery => Icons.delivery_dining_outlined,
      snacks => Icons.lunch_dining_outlined,
      alcohol => Icons.wine_bar_outlined,
      fuel => Icons.local_gas_station_outlined,
      evCharging => Icons.ev_station_outlined,
      publicTransit => Icons.directions_bus_outlined,
      taxi => Icons.local_taxi_outlined,
      parking => Icons.local_parking_outlined,
      tollRoads => Icons.confirmation_number_outlined,
      autoInsurance => Icons.policy_outlined,
      autoLoan => Icons.directions_car_outlined,
      vehicleMaintenance => Icons.car_repair_outlined,
      tireService => Icons.tire_repair_outlined,
      vehicleRegistration => Icons.description_outlined,
      carWash => Icons.local_car_wash_outlined,
      pharmacy => Icons.local_pharmacy_outlined,
      medicine => Icons.medication_outlined,
      doctor => Icons.medical_services_outlined,
      dentist => Icons.medical_services_outlined,
      visionCare => Icons.visibility_outlined,
      medicalTests => Icons.science_outlined,
      medicalProcedures => Icons.vaccines_outlined,
      healthInsurance => Icons.health_and_safety_outlined,
      mentalHealth => Icons.psychology_outlined,
      physiotherapy => Icons.accessibility_new_outlined,
      gymFitness => Icons.fitness_center_outlined,
      vitamins => Icons.spa_outlined,
      childcare => Icons.child_care_outlined,
      daycare => Icons.child_friendly_outlined,
      university => Icons.account_balance_outlined,
      tutoring => Icons.menu_book_outlined,
      babySupplies => Icons.child_friendly_outlined,
      toys => Icons.toys_outlined,
      childSupport => Icons.family_restroom_outlined,
      clothing => Icons.checkroom_outlined,
      shoes => Icons.hiking_outlined,
      cosmetics => Icons.face_retouching_natural_outlined,
      jewelry => Icons.diamond_outlined,
      haircare => Icons.content_cut_outlined,
      nailCare => Icons.back_hand_outlined,
      personalHygiene => Icons.soap_outlined,
      contactLenses => Icons.contact_page_outlined,
      movies => Icons.movie_outlined,
      theatre => Icons.theater_comedy_outlined,
      concerts => Icons.music_note_outlined,
      gaming => Icons.sports_esports_outlined,
      streaming => Icons.subscriptions_outlined,
      music => Icons.library_music_outlined,
      books => Icons.menu_book_outlined,
      hobbies => Icons.interests_outlined,
      travel => Icons.flight_takeoff_outlined,
      hotels => Icons.hotel_outlined,
      courses => Icons.school_outlined,
      onlineLearning => Icons.computer_outlined,
      universityTuition => Icons.account_balance_outlined,
      certifications => Icons.workspace_premium_outlined,
      conferences => Icons.event_outlined,
      languageCourses => Icons.translate_outlined,
      educationalMaterials => Icons.menu_book_outlined,
      bankFees => Icons.account_balance_outlined,
      atmFees => Icons.atm_outlined,
      creditCardPayment => Icons.credit_card_outlined,
      loanPayment => Icons.payments_outlined,
      debtRepayment => Icons.money_off_outlined,
      emergencyFund => Icons.health_and_safety_outlined,
      investments => Icons.trending_up_rounded,
      currencyExchange => Icons.currency_exchange_outlined,
      incomeTax => Icons.request_quote_outlined,
      driverLicence => Icons.directions_car_outlined,
      passport => Icons.card_travel_outlined,
      immigrationFees => Icons.language_outlined,
      permits => Icons.approval_outlined,
      governmentServices => Icons.account_balance_outlined,
      petFood => Icons.pets_outlined,
      veterinary => Icons.local_hospital_outlined,
      petMedicine => Icons.medication_outlined,
      petInsurance => Icons.health_and_safety_outlined,
      petGrooming => Icons.content_cut_outlined,
      petSupplies => Icons.inventory_2_outlined,
      gifts => Icons.card_giftcard_outlined,
      charity => Icons.volunteer_activism_outlined,
      donations => Icons.favorite_border_rounded,
      holidayExpenses => Icons.celebration_outlined,
      officeSupplies => Icons.inventory_2_outlined,
      software => Icons.code_outlined,
      equipment => Icons.devices_outlined,
      businessTravel => Icons.business_center_outlined,
      professionalMemberships => Icons.groups_outlined,
      licences => Icons.verified_outlined,
      cashWithdrawal => Icons.atm_outlined,
      adjustment => Icons.tune_outlined,
      bonus => Icons.card_giftcard_outlined,
      overtime => Icons.schedule_outlined,
      commission => Icons.percent_outlined,
      tips => Icons.restaurant_outlined,
      businessIncome => Icons.storefront_outlined,
      consulting => Icons.support_agent_outlined,
      rentalIncome => Icons.home_work_outlined,
      interestIncome => Icons.savings_outlined,
      dividendIncome => Icons.payments_outlined,
      capitalGains => Icons.trending_up_rounded,
      investmentDistribution => Icons.account_balance_wallet_outlined,
      taxRefund => Icons.receipt_long_outlined,
      governmentBenefits => Icons.account_balance_outlined,
      pension => Icons.elderly_outlined,
      childBenefit => Icons.child_care_outlined,
      employmentInsurance => Icons.health_and_safety_outlined,
      giftReceived => Icons.card_giftcard_outlined,
      familySupport => Icons.family_restroom_outlined,
      cashback => Icons.currency_exchange_outlined,
      rewards => Icons.emoji_events_outlined,
      refund => Icons.replay_outlined,
      reimbursement => Icons.receipt_long_outlined,
      saleOfItem => Icons.sell_outlined,
      otherIncome => Icons.payments_outlined,
      _ => Icons.category_outlined,
    };
  }
}
